server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations:
      - classpath:db/migrations
      - classpath:db/seeds
  jpa:
    hibernate:
      ddl-auto: none
